### ISSUE TITLE
query tool has option to only query OpenNeuro node but shows other options

### ISSUE THREAD

**Issue by surchs** [neurobagel/old-query-tool#281] opened 2023-11-16 14:21 UTC
For OpenNeuro we need to have a way to only query OpenNeuro data. But when we do that, users should also see that there are other node APIs they could also query by making a manual selection.

- [ ] prominent UI element that let's a user select which node-APIs to federate a query over.

**Comment by alyssadai** [comment] 2023-11-16 16:16
duplicate of #267

**Closed as completed by alyssadai** 2023-11-16 16:16 UTC
